# Generated by Django 4.2.6 on 2023-10-09 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id_ativo', models.AutoField(primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=10)),
                ('limite_inferior_tunnel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_superior_tunnel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidade_minutos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ativo')),
            ],
        ),
    ]
