# Generated by Django 4.2.6 on 2023-10-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id_ativo', models.AutoField(primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=10)),
                ('limite_inferior_tunnel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_superior_tunnel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidade_minutos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id_cotacao', models.AutoField(primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=50)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
