# Generated by Django 4.2.6 on 2023-10-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('de', models.EmailField(max_length=254)),
                ('para', models.EmailField(max_length=254)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
